concurrency: 16
run:
  deadline: 10m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number

linters-settings:
  godox:
    keywords:
      - FIXME

issues:
  max-same-issues: 0

linters:
  enable:
    - scopelint
    - govet
    - ineffassign
    - varcheck
    - unused
    - deadcode
    - bodyclose
    - structcheck
    - staticcheck
    - godox
    - rowserrcheck
    - prealloc

  disable-all: true
  fast: false
