concurrency: 16
run:
  deadline: 10m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number

linters-settings:
  gocritic:
    disabled-checks:
      - captLocal # CIDR, IpV6, ....
      - unlambda # falsePositive for function passed to defer
  godox:
    keywords:
      - FIXME

issues:
  max-same-issues: 0

  exclude-rules:

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA4004:" #https://staticcheck.io/docs/checks#SA4004 The loop exits unconditionally after one iteration

linters:
  enable:
    - scopelint
    - govet
    - ineffassign
    - varcheck
    - unused
    - deadcode
    - bodyclose
    - structcheck
    - staticcheck
    - godox

  # high priority
  #    - rowserrcheck
  #    - errcheck

  # normal priority
  #   - prealloc - jednotky


  # low priority
  #   - gosimple
  #   - gosec
  #   - goconst
  #   - gocritic
  #   - nakedret

  disable-all: true
  fast: false
