name: Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    name: Build && tests for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux amd64
            os: ubuntu-latest
            osEnv: GOOS=linux GOARCH=amd64
          - name: linux 386
            os: ubuntu-latest
            osEnv: GOOS=linux GOARCH=386
          - name: darwin amd64
            os: macos-latest
            osEnv: GOOS=darwin GOARCH=amd64

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: | 
        export GOPATH=$HOME/go
        ./tools/install.sh

    - name: Build
      run: env ${{ matrix.osEnv }} go build -v ./cmd/... ./src/...

    - name: Test
      run: env ${{ matrix.osEnv }} go test -v ./cmd/... ./src/...

    - name: Lint
      run: env ${{ matrix.osEnv }} gomodrun golangci-lint run  ./cmd/... ./src/... --verbose



