name: Upload build asset

on:
  release:
    types: [published]

jobs:
  build:
    name: Upload build asset for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            buildCmd: env GOOS=linux GOARCH=amd64 go build -o zcli-linux ./main.go
            file: zcli-linux
            args: --better
            strip: true
          - os: macos-latest
            buildCmd: env GOOS=darwin GOARCH=amd64 go build -o zcli-mac ./main.go
            file: zcli-mac
            args: --better
            strip: false

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          export GOPATH=$HOME/go
          ./tools/install.sh

      - name: Build
        run: ${{ matrix.buildCmd }}

      - name: Compress binary
        uses: svenstaro/upx-action@v1-release
        with:
          file: ./${{ matrix.file }}

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.file }}
          asset_name: ${{ matrix.file }}
          asset_content_type: application/octet-stream
